<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>datePicker</name>
   <tag></tag>
   <elementGuidId>77f682bd-d0a7-4e1b-b5d2-6f07d3c40886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#refDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#refDate</value>
   </webElementProperties>
</WebElementEntity>
