<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeBdayDatePickerItem</name>
   <tag></tag>
   <elementGuidId>436cabe9-bfda-4a7e-899f-ebb70bc5b1ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#birthdate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#birthdate</value>
   </webElementProperties>
</WebElementEntity>
