<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>refTime</name>
   <tag></tag>
   <elementGuidId>849946af-c71f-4dc9-85b8-8256016c37dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#referral_time</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#referral_time</value>
   </webElementProperties>
</WebElementEntity>
