<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_title</name>
   <tag></tag>
   <elementGuidId>0fa798e2-13eb-40c3-b6dd-8a5b63b165d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#title</value>
   </webElementProperties>
</WebElementEntity>
