<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zip_code</name>
   <tag></tag>
   <elementGuidId>435555f5-9695-4f96-91ea-faedfa3d28e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#zipCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#zipCode</value>
   </webElementProperties>
</WebElementEntity>
