<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>offset</name>
   <tag></tag>
   <elementGuidId>e2ae850f-5a5a-499e-983d-394284ab79c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#data-table-command-footer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#data-table-command-footer</value>
   </webElementProperties>
</WebElementEntity>
