<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>no</name>
   <tag></tag>
   <elementGuidId>e5a914f7-e5aa-4cd5-995d-ee708f1b0b16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;content&quot;]/data/div[2]/div/form/fieldset/div/table/tbody/tr[13]/td[2]/div/label[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;content&quot;]/data/div[2]/div/form/fieldset/div/table/tbody/tr[13]/td[2]/div/label[2]/input</value>
   </webElementProperties>
</WebElementEntity>
