<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>time_out</name>
   <tag></tag>
   <elementGuidId>d86f0d0d-8ba9-423b-b593-bf0e85f00f63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#to</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#to</value>
   </webElementProperties>
</WebElementEntity>
