<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>time_in</name>
   <tag></tag>
   <elementGuidId>f3e49682-ad5e-4dea-ab05-08821d496f08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ti</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ti</value>
   </webElementProperties>
</WebElementEntity>
