<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>visit_date</name>
   <tag></tag>
   <elementGuidId>89d8cb9f-d8c3-4746-ab4f-4c6c1c0a565b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#visitDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#visitDate</value>
   </webElementProperties>
</WebElementEntity>
