<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title</name>
   <tag></tag>
   <elementGuidId>31b8a649-e65f-4238-81e0-9c2046a100ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#title</value>
   </webElementProperties>
</WebElementEntity>
