<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zip_code</name>
   <tag></tag>
   <elementGuidId>46e59342-4eca-4f1f-b9c3-68367a0b338c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#zipCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#zipCode</value>
   </webElementProperties>
</WebElementEntity>
