<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_edit</name>
   <tag></tag>
   <elementGuidId>1ccc5d60-04db-4198-bb5c-e439d7e03653</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#title</value>
   </webElementProperties>
</WebElementEntity>
