<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M0016</name>
   <tag></tag>
   <elementGuidId>5d87c336-9d26-4bf7-b3d5-44c5d130f76f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#M0016</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#M0016</value>
   </webElementProperties>
</WebElementEntity>
