<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M0090</name>
   <tag></tag>
   <elementGuidId>38b42c4f-2ecd-49f0-a140-66ecb44ab67e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#m0090_info_completed_dt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#m0090_info_completed_dt</value>
   </webElementProperties>
</WebElementEntity>
