<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M0104</name>
   <tag></tag>
   <elementGuidId>cfcaffee-6fbe-41ea-8660-3e39fadd8b5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#m0104_physn_rfrl_dt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#m0104_physn_rfrl_dt</value>
   </webElementProperties>
</WebElementEntity>
