<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M0150-Insurancelist</name>
   <tag></tag>
   <elementGuidId>367dc3d0-a6d1-4276-af1b-dcd8fe6c27cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#primary_insurance_chosen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#primary_insurance_chosen</value>
   </webElementProperties>
</WebElementEntity>
