<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1005-date</name>
   <tag></tag>
   <elementGuidId>a201a67b-f244-4146-ae86-a3b71f39a188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#m1005_inp_discharge_dt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#m1005_inp_discharge_dt</value>
   </webElementProperties>
</WebElementEntity>
